CustomerManagement/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns = [
    path('',views.home,name='home'),
    path('products/',views.products,name='products'),
    path('customer/<str:pk_test>',views.customer, name='customer'),
    path('create_order/<str:pk>', views.createOrder, name='create_order'),
    path('update_order/<str:pk>', views.updateOrder, name='update_order'),
    path('delete_order/<str:pk>', views.deleteOrder, name='delete_order'),
    path('login/', views.login_view, name='login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('logout_view/', views.logout_view, name='logout'),
    path('user/', views.userPage, name='user'),
    path('setting/', views.accountSettings, name='setting'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    email =models.EmailField(max_length=255,null=True)
    profile_pic=models.ImageField(null=True, blank=True)
    date_crreated = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self) -> str:
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255, null=True)

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    CATEGORY =(
        ('Indoor', 'I'),
        ('Outdoor', 'O'),
       
    ) 
    name = models.CharField(max_length=255, null=True)
    price = models.FloatField(max_length=255, null=True)
    category = models.CharField(max_length=255, null=True, choices=CATEGORY)
    description = models.CharField(max_length=255, null=True)
  
    tags = models.ManyToManyField(Tag)

    def __str__(self):
       return self.name
STATUS =(
    ('Pending','Pending'),
    ('out of delivery','out of delivery'),
    ('Delivered','Delivered'),

)



class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    product =  models.ForeignKey(Product,on_delete=models.SET_NULL, null=True)
    status=models.CharField(max_length=255, choices=STATUS,null=True)
    date_created=models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self) -> str:
        return self.product.name

accounts/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms

# Example OrderForm


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['product','status']


class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']


class CustomerForm(forms.ModelForm):
    class Meta:
        model= Customer
        fields='__all__'
        exclude=['user']

accounts/views.py
from django.shortcuts import render, redirect
from . models import *
from .forms import *
from .filters import OrderFilter
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.contrib.auth.models import Group

# Create your views here.
@login_required(login_url='accounts:login')
@admin_only
def home(request):
    customers=Customer.objects.all()
    orders = Order.objects.all()
    total_customers=customers.count()
    total_orders=orders.count()
    delivered=orders.filter(status='Delivered').count()
    pending=orders.filter(status='Pending').count()
    context ={
        'customers':customers,
        'orders':orders,
        'total_customers':total_customers,
        'total_orders':total_orders,
        'delivered':delivered,
        'pending':pending
    }

    return render(request,'accounts/dashboard.html',context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all() 
    # context=products
    return render(request, 'accounts/products.html',{'products':products})


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer(request,pk_test): 
    customer=Customer.objects.get(id=pk_test)
    orders=customer.order_set.all()
    total_orders=orders.count()
    myFilter = OrderFilter(request.GET, queryset=orders)
    orders=myFilter.qs
    context={
        'customer':customer,
        'orders':orders,
        'total_orders':total_orders,
        'myFilter':myFilter
    }
    return render( request, 'accounts/customer.html',context)


def createOrder(request,pk):
    customer = Customer.objects.get(id=pk)
    print(customer)

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order=form.save(commit=False)
            order.customer=customer
            order.save()

            return redirect('accounts:home')
    else:
        form = OrderForm()
        context={
        'form': form,

                    }
        return render(request,'accounts/order_form.html',context)
    

def updateOrder(request, pk):

	order = Order.objects.get(id=pk)
	form = OrderForm(instance=order)

	if request.method == 'POST':
		form = OrderForm(request.POST, instance=order)
		if form.is_valid():
			form.save()
			return redirect('/')

	context = {'form': form}
	return render(request, 'accounts/order_form.html', context)

def deleteOrder(request,pk) :
     order = Order.objects.get(id=pk)
     if request.method == 'POST':
          order.delete()
          return redirect('accounts:home')
     context={'item':order}
     return render(request,"accounts/delete.html", context)


@unauthorized_users
def sign_up(request):
  
   form = CreateUserForm()
   if request.method == 'POST':

     form = CreateUserForm( request.POST)
     if form.is_valid():
          user=form.save()
          group = Group.objects.get(name='customer')
          user.groups.add(group)
          Customer.objects.create(user=user)

          user=form.cleaned_data.get('username')
          messages.success(request,'account  created'+ user)
          return redirect('accounts:login')
     


  
        
   
   context={
         'form':form
              }
   return render(request,'accounts/sign_up.html',context)


@unauthorized_users
def login_view(request):

    if request.method == 'POST':
          
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # Redirect to a success page.
            return redirect('accounts:home') 
        else:
             messages.info(request, 'password or username incorrect')
    
    form = AuthenticationForm()
    context= {
          'form':form
            }
    return render(request,'accounts/login.html',context)


def logout_view(request):
     
          logout(request)
          return redirect('accounts:login')
     

@allowed_users(allowed_roles=['customer'])
def userPage(request):
     orders = request.user.customer.order_set.all()
     
     total_orders=orders.count()
     delivered=orders.filter(status='Delivered').count()
     pending=orders.filter(status='Pending').count()
     context={'orders':orders,
              'total_orders':total_orders,
              'pending': pending,
              'delivered': delivered

          
              
              }

     return render(request,'accounts/user.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def accountSettings(request):
     customer = request.user.customer
     form = CustomerForm(instance=customer)
     if request.method == 'POST':
          form=CustomerForm(request.POST, request.FILES,instance=customer)
          if form.is_valid():
               form.save()
     context = {'form':form}

     return render(request, 'accounts/accounts_setting.html',context)

accounts/templates/accounts/accounts_setting.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<style>
    .profile-pic {
        max-width: 200px;
        max-height: 200px;
        margin: 0 auto;
        border-radius: 50%;
    }
</style>

<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            <a class="btn btn-warning" href="{% url 'accounts:home' %}"> &#8592; Back to Profile</a>
            <hr>
            <h3 style="text-align: center">Account Settings</h3>
            <hr>
            <img class="profile-pic" src="{{request.user.customer.profile_pic.url}}">

        </div>
    </div>
    <div class="col-md-9">
        <div class="card card-body">

            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                <input class="btn btn-primary" type="submit" name="Update Information">
            </form>
        </div>
    </div>
</div>



{% endblock %}

accounts/templates/accounts/customer.html
{% extends 'accounts/main.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Customer:</h5>
            <hr>
            <a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a>
            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:create_order' customer.id%}">create order</a>

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{customer.email}}</p>
            <p>Phone: {{customer.phone}}</p>
        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px">{{total_orders}}</h1>
        </div>
    </div>
</div>


<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
                {{myFilter.form}}

                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>

</div>
<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{order.product}}</td>
                    <td>{{order.product.category}}</td>
                    <td>{{order.date_created}}</td>
                    <td>{{order.status}}</td>
                    <td><a href="{% url 'accounts:update_order' order.id %}" class="btn btn-info">update</a></td>
                    <td><a href="{%url 'accounts:delete_order' order.id %}" class="btn btn-danger">Delete</a></td>

                </tr>
                {% endfor%}

            </table>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}

{% block content %}

{% include 'accounts/status.html' %}

<br>

<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>
            <table class="table table-sm">
                <tr>
                    <th>Detail</th>
                    <th>Customer</th>
                    <th>phone</th>
                </tr>

                {% for customer in customers %}
               
                <tr>
                    <td><a class="btn btn-small btn-info" href="{% url 'accounts:customer' customer.id %}">view</a></td>
                    <td>{{customer.name}}</td>
                    <td>{{customer.phone}}</td>
                    
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5>LAST 5 ORDERS</h5>
        <hr>
        <div class="card card-body">
           
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{order.product.name}}</td>
                    <td>{{order.date_created}}</td>
                    <td>{{order.status}}</td>
                    <td><a href="{% url 'accounts:update_order' order.id %}" class="btn btn-info">update</a></td>
                    <td><a href="{%url 'accounts:delete_order' order.id %}" class="btn btn-danger">Delete</a></td>
                  
                    
                
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">


            <p>Are you sure you want to delete "{{item}}"?</p>

            <form action="{% url 'accounts:delete_order' item.id  %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'accounts:home' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>

                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>

                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>

                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor %}
                  
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'accounts:sign_up' %}" class="ml-2">Sign Up</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

accounts/templates/accounts/main.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>CRM</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="{% static '/css/main.css' %}" >
    
</head>

<body>
    {% include 'accounts/navbar.html' %}
    <div class="container-fluid">
        {% block content %}



        {% endblock %}
    </div>
    <hr>
    <h5>Our footer</h5>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</html>

accounts/templates/accounts/navbar.html
{% load static %}

<style>
    .hello-msg{
        font-size: 18px;
        color:#fff;
        margin-right:20px;

    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="{% static 'images/logo.png' %}" alt="">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        {%  if request.user.is_staff %}
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:home'%}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
            </li>
        {%  else %}
            <li class="nav-item">
                <a class=" hello-msg" href="{% url 'accounts:setting' %}">Settings</a>

            </li>
        </ul>
        {% endif  %}
    </div>
    <span class="hello-msg">Hello, {{request.user}}</span>
    <span><a class="hello-msg" href="{% url 'accounts:logout'%}">logout</a></span>
</nav>

accounts/templates/accounts/order_form.html
{% extends 'accounts/main.html' %}

{% block content %}

<h1>welcome to the order form </h1>
<form action="" method="post">
    {% csrf_token %}
      {{form}}
    <input type="submit" name="submit">
</form>
{% endblock %}

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>

                {% for i in products %}
                <tr>
                    <td>{{i.name}}</td>
                    <td>{{i.category}}</td>
                    <td>{{i.price}}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>

</div>

{% endblock content %}

accounts/templates/accounts/sign_up.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>



                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>

                    </form>
                </div>
                   {{form.errors}}

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder = 'Username..';
        form_fields[2].placeholder = 'Email..';
        form_fields[3].placeholder = 'Enter password...';
        form_fields[4].placeholder = 'Re-enter Password...';


        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>
</body>

</html>

accounts/templates/accounts/status.html
<br>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{total_orders}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{delivered}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{pending}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/user.html
{% extends 'accounts/main.html' %}

{% block content %}

{% include 'accounts/status.html' %}


<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{order.product}}</td>
                    <td>{{order.product.category}}</td>
                    <td>{{order.date_created}}</td>
                    <td>{{order.status}}</td>
                    <!-- <td><a href="{% url 'accounts:update_order' order.id %}" class="btn btn-info">update</a></td>
                    <td><a href="{%url 'accounts:delete_order' order.id %}" class="btn btn-danger">Delete</a></td> -->

                </tr>
                {% endfor%}

            </table>
        </div>
    </div>
</div>

{% endblock %}